### ISSUE TITLE
A tiny little data type bug complain by XCode 6

### ISSUE THREAD

**Issue by remaerd** [RNCryptor/RNCryptor#125]
Thanks for your frameworks.
XCode 6 is complaining that the RNOpenSSLCrytor.m, line 80. is having a data type error. The key variable is NSMutableData but it try to initialize as a NSData Object.

**Comment by rnapier** [comment]
see also #138. OpenSSL support has been moved to https://github.com/rnapier/RNOpenSSLCryptor and is no longer actively supported.
