### ISSUE TITLE
Non-passive change from 2.1 -> 2.2

### ISSUE THREAD

**Issue by LowAmmo** [RNCryptor/RNCryptor#141]
Just wanted to raise awareness that the change to the struct:

#### Old:
    typedef struct _RNCryptorKeyDerivationSettings
    {
      size_t keySize;
      size_t saltSize;
      CCPBKDFAlgorithm PBKDFAlgorithm;
      CCPseudoRandomAlgorithm PRF;
      uint rounds;
    } RNCryptorKeyDerivationSettings;

#### New:
    typedef struct _RNCryptorKeyDerivationSettings
    {
      size_t keySize;
      size_t saltSize;
      CCPBKDFAlgorithm PBKDFAlgorithm;
      CCPseudoRandomAlgorithm PRF;
      uint rounds;
      BOOL hasV2Password;
    } RNCryptorKeyDerivationSettings;

That adds a new BOOL value can cause issues if anyone is in any sort of a mixed environment where some libraries might be using an older version of RNCrypter.

Obviously, nothing can be done, now, but I wasn't sure the best place to 'raise the flag' just so any other developers running into the situation we just ran into have at least some advanced knowledge.

**Comment by rnapier** [comment]
It is very dangerous for libraries to embed other libraries for exactly this reason. No library should itself link RNCryptor. It is the job of the application to link all of the libraries together at the end.
