### ISSUE TITLE
HMAC Mismatch iOS (not PHP decryption)

### ISSUE THREAD

**Issue by jasper-ch-chan** [RNCryptor/RNCryptor#145]
So I'm currently running into HMAC Mismatch errors and I believe I know the issue... I am hoping someone here would be able to propose a solution.

Heres the general situation as to what I am experiencing:

NSData* someData = "Some data of 512k byte size";
NSData* encryptData = [RNCryptor encryptData:someData withSettings: AES256 withPassword:"Hello"];
NSFileHandler* file;
[file writeData:encryptData];
[file closeFile];

The problem starts here... encryptData will be of a random size larger than 512k byte due to the encryption (lets just say 515k bytes). When I try to decrypt the same file...

NSData* 512kChunkData = "Some encrypted NSData of 512k byte size";
NSData* decryptData = [RNDecryptor decryptData:512kChunkData withPassword:"Hello"];

decryptData will give me the error of HMAC Mismatch because I'm not actually grabbing the correct chunk size.

Thoughts/Suggestions?

**Comment by rnapier** [comment]
I don't think I quite understand the question. You need to pass all of the data returned by the encryptor to the decryptor. The HMAC error is telling you that you didn't do that. Do you mean that you're streaming the data and need to decrypt in blocks? There's an asynchronous interface to handle that. But you can't just throw away some of the data.

**Comment by jasper-ch-chan** [comment]
Hi Rob,

Thanks for responding to my question. So I've realized that in my example, in order to successfully decrypt the block, I need to grab a size of 515k bytes because when I encrypted my 512k block, the RNCryptor returns a 515k byte block (these numbers were arbitrarily assigned). 

My question is, what is the best way so I can always grab the right block size to decrypt successfully? Currently, I am implementing a method to add 4 bytes of NSData as a header for each block I write to the device to hold the number of bytes I need to read (ie. 515k bytes) in order to successfully decrypt the block. The entire encrypted file is on the device and I am trying to write the decrypted version back onto the device at this point in time.

**Comment by rnapier** [comment]
The RNCryptor format is designed to be a whole-file format. It's not really designed to encrypt individual blocks within a larger file. But if you're using it that way, then a wrapper header sounds fine.

Random access encryption is a specialized problem. There are definitely ways to do it, but it isn't the goal of RNCryptor.

**Comment by jasper-ch-chan** [comment]
Thank you very much for your quick reply! I was just wondering if there was a better/easier way to handle this. Thanks again!
