### ISSUE TITLE
Is there a way to detect if a file is encrypted?

### ISSUE THREAD

**Issue by jasper-ch-chan** [RNCryptor/RNCryptor#150]
The situation is during app operation, the app crashes and it was unable to encrypt a certain file on the device. The assumption of the app is that everything on the device should be encrypted at all times. I was wondering if there is a way to determine if a file is encrypted? I noticed if I try to forcibly decrypt an unencrypted file, an Unknown Header exception is returned. I don't suppose it is a good idea to use this exception to determine whether or not a file is encrypted as it is too general of an exception?

Thanks in advanced!

**Comment by rnapier** [comment]
Currently there is no reliable way to detect encryption. You can easily
detect that something *isn't* encrypted, but there is a high false-positive
rate determining that things *are* encrypted. If the first two bytes aren't
either 0x0300 or 0x0301, then you know it isn't RNCryptor (0x0300 is
key-encrypted; 0x0301 is password-encrypted).

One of the goals of the v4 format was to make this a little more reliable
by putting a few bytes of magic at the start.

I'm a little confused by the use case. If "everything on the device should
be encrypted at all times," then why would this ever be a question?

If this is a major issue, you can always wrap the RNCryptor data in an
envelope. Just put a few bytes at the front of the file that indicates its
status. Or use different file names.

**Comment by jasper-ch-chan** [comment]
Hello Rob,

Thank you very much for your swift reply. The reason why this case is a concern for us because while the app was encrypting a file, the app crashed. When the app was restarted, the temporary folder was deleted and the file left behind (assumed to be encrypted) is left unencrypted.

So are you suggesting that I check the first two bytes of the file for 0x0300 or 0x0301 such that if the first two bytes correspond to either of them, then we know for a fact that the file *is* encrypted?

**Comment by rnapier** [comment]
If your goal is to always have the file encrypted, I would never write it
unencrypted in the first place. See the "Asynchronous usage" section if you
need to encrypt as you go (for example during download). It's not as simple
to use as I'd like, but it's the tool for this.

So are you suggesting that I check the first two bytes of the file for
> 0x0300 or 0x0301 such that if the first two bytes correspond to either of
> them, then we know for a fact that the file is encrypted?


No, I'm saying if the first two bytes are *not* one of those two pairs,
then it is not RNCryptor data. It is completely legal for a file to have
those first two bytes and have nothing to do with RNCryptor. (That's
actually true of any leading header, but the longer the header the more
likely you won't have a collision.) If you know something about the files
you're encrypting, then you may be able to know that they will never start
with those two bytes and use that information.

**Comment by jasper-ch-chan** [comment]
Thank you very much for your information. I will review "Asynchronous usage" section again. Thank you once again!
