### ISSUE TITLE
Issue encrypting on iOS then decrypting on PHP

### ISSUE THREAD

**Issue by ad1269** [RNCryptor/RNCryptor#153]
Hi I'm having a problem when encrypting my data on iPhone then decrypting it on PHP. My iPhone code throws no errors and neither does my PHP, but when I put them together, it throws out a bunch of errors. I used a wrapper class to encrypt because using the kRNCryptorAES256Settings constant threw a bunch of errors for me.

Here's my encryption code:

    var myMessage = "This is my top secret message!"
    let myPassword = "cool"
    let myData = myMessage.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!
    let eData = ACEncryptor.encryptData(myData, password: myPassword, error: nil)

   //Send to server

Decryption code:

   require __DIR__.'/autoload.php';
   $aes = new \RNCryptor\Decryptor();
   $data = $aes->decrypt($eData, $password);

The error that the php throws out is below. It returned it in the terminal of my app so there are a lot of html tags.

<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Unsupported schema version 211' in /home/u350976909/public_html/lib/RNCryptor/Cryptor.php:70
Stack trace:
#0 /home/u350976909/public_html/lib/RNCryptor/Decryptor.php(66): RNCryptor\Cryptor-&gt;_configureSettings(211)
#1 /home/u350976909/public_html/lib/RNCryptor/Decryptor.php(49): RNCryptor\Decryptor-&gt;_parseHeaders('\xD3}5\xD7V\xF4s\xBD\x9B\xE9\xB6\xFC\xDD\xEE\xFA...')
#2 /home/u350976909/public_html/lib/RNCryptor/Decryptor.php(22): RNCryptor\Decryptor-&gt;_unpackEncryptedBase64Data('&lt;030111b0 c72b6...')
#3 /home/u350976909/public_html/Decrypt.php(62): RNCryptor\Decryptor-&gt;decrypt('&lt;030111b0 c72b6...', 'cool')
#4 {main}
  thrown in <b>/home/u350976909/public_html/lib/RNCryptor/Cryptor.php</b> on line <b>70</b><br />

Thanks in advance!

**Comment by rnapier** [comment]
Looks like your message is corrupt. You need to make sure that you're decrypting exactly the output of the encryptor. The common mistake is to fail to correctly convert between data and base64 encoded strings.

**Comment by ad1269** [comment]
Oh! I didn't realize that I forgot to convert my data to a base64 encoded string before sending it to the server! I added this line:
                   let eStr = eData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(0))
and it now works. Thank you!
