### ISSUE TITLE
How can i set IV(initialization vector) to some fix value rather than random, in decryption using AES

### ISSUE THREAD

**Issue by hadwanihardik** [RNCryptor/RNCryptor#154]
How can i set IV(initialization vector) to some fix value rather than random, in decryption using AES

**Comment by rnapier** [comment]
This doesn't make sense for decryption. RNCryptor includes the IV in the header, so the decryptor knows what it is. Do you mean for encryption?

For encryption there's a method that accepts the IV, but it should generally only be used in testing. It's difficult to use this method without breaking your security.

initWithSettings:encryptionKey:HMACKey:handler:

Except for testing, I can't imagine a use for calling this method. What are you doing?

**Comment by hadwanihardik** [comment]
Hello rob,

Encryption is currently done with encryption mechanism is AES_CBC_PKCS5 with 128 bit Key "Key" and Dynamic initialization vector 00000000000000000000000000000000.

can you suggest me how i can use this algorithm to decrypt my file  for above given encryption specs.

**Comment by rnapier** [comment]
Your format is not compatible with RNCryptor, and you can't use RNCryptor
to read or write this. If you must use this format, you will need to
implement your own system using CommonCryptor.

Note that your format has several security problems, including weak
encryption of at least the first block (possibly more depending on your
data format), lack of authentication (so third parties who know or can
guess the plaintext can modify your messages in predictable ways), and
possible vulnerability to padding oracle attacks. Preventing these kinds of
security problems are why I developed RNCryptor in the first place.

-Rob

**Comment by ernestopino** [comment]
Hello @rnapier... I need some help.

I need to encrypt with AES 256 a string with the following specifications:

- Key
- Vector: Vector empty, the 16 positions to 0.
- Format: CBC.

How I can set RNEncryptor to get this?
Thanks in advance,

**Comment by rnapier** [comment]
@ernestopino I believe this is precisely the question I answered two comments ago. See also the newly created [FAQ](https://github.com/RNCryptor/RNCryptor/tree/swift#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format).

Note that your encryption format has security flaws in at least the first block, and potentially additional blocks depending on their contents. It is not strong encryption.

**Comment by ernestopino** [comment]
Thank you very much for the speed of response and forgive my poor knowledge on the subject.

As you commented earlier, I am using `encryptData:withSettings:encryptionKey:HMACKey:IV:error:` to get a personalized encryption, the vulnerability that entails (IV = NULL or zeroed bytes). The problem is that I do not know what HMACKey use.

```
NSString *valueString = @"Asdfg1234";
NSString *keyString = @"1234";
    
NSData *valueData = [value dataUsingEncoding:NSUTF8StringEncoding];
NSData *keyData = [key dataUsingEncoding:NSUTF8StringEncoding];
NSMutableData *iv = [NSMutableData dataWithLength:16];
NSError *error;
    
NSData *encryptedData = [RNEncryptor encryptData:valueData
                                    withSettings:kRNCryptorAES256Settings
                                   encryptionKey:keyData
                                         HMACKey: ???
                                              IV:iv
                                           error:&error];
```

**Comment by rnapier** [comment]
@ernestopino I've updated the repository with [examples](https://github.com/RNCryptor/RNCryptor/blob/master/Examples/KeyDerivation.xcworkspace/KeyDerivation.playground/Contents.swift) of how to correctly generate keys for RNCryptor. This was writing for the latest (Swift) version, but will also work for the ObjC implementation.

Note that you're generating `keyData` incorrectly from `keyString`. The example demonstrates how to correctly convert a password into a key. (`keyString` in your example is not a key; it's a password.)
