### ISSUE TITLE
Strongest encryption setting available?

### ISSUE THREAD

**Issue by billychasen** [RNCryptor/RNCryptor#155]
Hi, I'm curious what other things I might want to change for "ridiculously strong"™ encryption. I just changed PRF to SHA512 and went up to 20,000 iterations. I know out of the box is incredibly strong, but I'd like to reach paranoid levels. Thanks!

```
static const RNCryptorSettings kNewSettings = {
    .algorithm = kCCAlgorithmAES128,
    .blockSize = kCCBlockSizeAES128,
    .IVSize = kCCBlockSizeAES128,
    .options = kCCOptionPKCS7Padding,
    .HMACAlgorithm = kCCHmacAlgSHA256,
    .HMACLength = CC_SHA256_DIGEST_LENGTH,

    .keySettings = {
        .keySize = kCCKeySizeAES256,
        .saltSize = 8,
        .PBKDFAlgorithm = kCCPBKDF2,
        .PRF = kCCPRFHmacAlgSHA512,
        .rounds = 20000
    },

    .HMACKeySettings = {
        .keySize = kCCKeySizeAES256,
        .saltSize = 8,
        .PBKDFAlgorithm = kCCPBKDF2,
        .PRF = kCCPRFHmacAlgSHA512,
        .rounds = 20000
    }
};
```

**Comment by rnapier** [comment]
Changing the keySettings PRF has no effect on security. Any collision resistant has there is equivalent. Using MD5 wouldn't reduce security. The ability for attackers to generate collisions on the hash is irrelevant to PBKDF2's security proof. But set it any way you like. 

Increasing the number of iterations is the #1 most impactful thing you can do. 1,000,000 iterations is not an absurd setting. 

Better is to forbid passwords entirely and generate totally random encryption and hmac keys. That's most secure and much, much faster. 

Those are really the only tunable things that make sense to adjust IMO.

**Comment by billychasen** [comment]
Cool, thanks so much for such an easy lib, it's working great.
