### ISSUE TITLE
Can't compile project once I included RNCryptor: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by cojomojo** [RNCryptor/RNCryptor#156]
I created a fresh xcode project targeting iOS. I downloaded the RNCryptor repo, copied the RNCryptor files into my project, included the header file "RNEncryptor.h" in my ViewController.m, and tried out some simple code:

```obj-c
NSString *aPassword = @"Some string";
    NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
    NSError *error;
    NSData *encryptedData = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptorAES256Settings
                                            password:aPassword
                                               error:&error];
```

When I build the project for the ios simulator I get

```
Apple Mach-O Linker Error
  "_OBJC_CLASS_$_RNEncryptor", 
referenced from: 
```

and specifically: 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RNEncryptor", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
```

I went into the target's build settings and changed "Build Active Architectures Only" to No. The "valid architectures" listed are "arm64, armv7, armv7s". The "architectures" field is set to Standard Architectures (armv7, amr64) - $ARCH_STANDARD".  I am using Xcode 6.3.2. Any help or ideas on what is causing this would be appreciated.

**Comment by rnapier** [comment]
The most common cause of this is not making the .m files part of your target. In the inspector (right hand pane), make sure there's a check mark for each target you want for each .m

**Comment by cojomojo** [comment]
That was indeed the issue. Thanks.
