### ISSUE TITLE
Encryption setting with triple DES

### ISSUE THREAD

**Issue by evan0322** [RNCryptor/RNCryptor#158]
Hi,

For some reason I have to use 3 DES encryption for my data. But It seems that I cannot correctly encrypt/decrypt data. For the setting, I create a instance kRNCryptor3DESSettings:

```
static const RNCryptorSettings kRNCryptor3DESSettings = {
    .algorithm = kCCAlgorithm3DES,
    .blockSize = kCCBlockSize3DES,
    .IVSize = kCCBlockSize3DES,
    .options = kCCOptionPKCS7Padding,
    .HMACAlgorithm = kCCHmacAlgSHA1,
    .HMACLength = CC_SHA1_DIGEST_LENGTH,
    
    .keySettings = {
        .keySize = kCCKeySize3DES,
        .saltSize = 8,
        .PBKDFAlgorithm = kCCPBKDF2,
        .PRF = kCCPRFHmacAlgSHA1,
        .rounds = 10000
    },
    
    .HMACKeySettings = {
        .keySize = kCCKeySize3DES,
        .saltSize = 8,
        .PBKDFAlgorithm = kCCPBKDF2,
        .PRF = kCCPRFHmacAlgSHA1,
        .rounds = 10000
    }
};
```
and call 

```
NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
    NSData *encryptedtestData = [RNEncryptor encryptData:data
                                        withSettings:kRNCryptor3DESSettings
                                            password:@"test"
                                               error:&error];
    
    NSData *decryptedData = [RNDecryptor decryptData:encryptedtestData
                                        withPassword:@"test"
                                               error:&error];
```
The decryptedData is always nil. Can anyone help me check if the 3 DES settings is not correct? Thanks!!

**Comment by rnapier** [comment]
You're using decryptData:withPassword:error. You would have to use
decryptData:withSettings:password:error:. Otherwise the decryptor doesn't
know your settings.

I have not yet been able to imagine a situation where this requirement
makes sense in conjunction with using RNCryptor. The security of 3DES is
sufficient for many situations, so this isn't necessarily a broken system
or anything. I just can't really imagine the chain of events that would
lead to needing 3DES and also needing RNCryptor. That said, I don't see any
reason it wouldn't work.

-Rob


On Wed, Aug 26, 2015 at 6:20 PM, Wei <notifications@github.com> wrote:

> Hi,
>
> For some reason I have to use 3 DES encryption for my data. But It seems
> that I cannot correctly encrypt/decrypt data. For the setting, I create a
> instance kRNCryptor3DESSettings:
>
> static const RNCryptorSettings kRNCryptor3DESSettings = {
>     .algorithm = kCCAlgorithm3DES,
>     .blockSize = kCCBlockSize3DES,
>     .IVSize = kCCBlockSize3DES,
>     .options = kCCOptionPKCS7Padding,
>     .HMACAlgorithm = kCCHmacAlgSHA1,
>     .HMACLength = CC_SHA1_DIGEST_LENGTH,
>
>     .keySettings = {
>         .keySize = kCCKeySize3DES,
>         .saltSize = 8,
>         .PBKDFAlgorithm = kCCPBKDF2,
>         .PRF = kCCPRFHmacAlgSHA1,
>         .rounds = 10000
>     },
>
>     .HMACKeySettings = {
>         .keySize = kCCKeySize3DES,
>         .saltSize = 8,
>         .PBKDFAlgorithm = kCCPBKDF2,
>         .PRF = kCCPRFHmacAlgSHA1,
>         .rounds = 10000
>     }
> };
>
> and call
>
> NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
>     NSData *encryptedtestData = [RNEncryptor encryptData:data
>                                         withSettings:kRNCryptor3DESSettings
>                                             password:@"test"
>                                                error:&error];
>
>     NSData *decryptedData = [RNDecryptor decryptData:encryptedtestData
>                                         withPassword:@"test"
>                                                error:&error];
>
> The decryptedData is always nil. Can anyone help me check if the 3 DES
> settings is not correct? Thanks!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RNCryptor/RNCryptor/issues/158>.
>



-- 
Rob Napier
Cocoaphony blog -- http://robnapier.net/blog
iOS Programming Pushing the Limits -- http://robnapier.net/book

**Comment by evan0322** [comment]
Hi Rob,

Thank you for your reply. I got it. But just a little curious. In the documentation of RDCryptor it is said 
*
This generates an NSData including a header, encryption salt, HMAC salt, IV, ciphertext, and HMAC. To decrypt this bundle:

NSData *decryptedData = [RNDecryptor decryptData:encryptedData
                                    withPassword:aPassword
                                           error:&error];
Note that RNDecryptor does not require settings. These are read from the header.

*

So from what you said I believe the header is not applied to 3DES encryption ?

**Comment by rnapier** [comment]
The header does not include most of the settings.
decryptData:withPassword:error: assumes you use standard settings.

It was a mistake on my part to make settings user configurable. RNCryptor
was never designed to work with modified settings. RNCryptor defines a
specific format with just a couple of things that can be modified.

-Rob


On Thu, Aug 27, 2015 at 9:34 AM, Wei <notifications@github.com> wrote:

> Hi Rob,
>
> Thank you for your reply. I got it. But just a little curious. In the
> documentation of RDCryptor it is said
> *
> This generates an NSData including a header, encryption salt, HMAC salt,
> IV, ciphertext, and HMAC. To decrypt this bundle:
>
> NSData *decryptedData = [RNDecryptor decryptData:encryptedData
> withPassword:aPassword
> error:&error];
> Note that RNDecryptor does not require settings. These are read from the
> header.
>
> *
>
> So from what you said I believe the header is not applied to 3DES
> encryption ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RNCryptor/RNCryptor/issues/158#issuecomment-135430397>
> .
>



-- 
Rob Napier
Cocoaphony blog -- http://robnapier.net/blog
iOS Programming Pushing the Limits -- http://robnapier.net/book

**Comment by evan0322** [comment]
Cool. Thanks for sorting this out. I will close this for now.
