### ISSUE TITLE
RNCryptor >> Example >> encrypt.php Not working 

### ISSUE THREAD

**Issue by imobdeveloper** [RNCryptor/RNCryptor#165]
require __DIR__.'/../autoload.php';

$password = "testing";
$plaintext = "Here is my test vector. It's not too long, but more than a block and needs padding.";

echo "This text has print";

$cryptor = new \RNCryptor\Encryptor();

echo "This text has not printing ";

$base64Encrypted = $cryptor->encrypt($plaintext, $password);
print_r($base64Encrypted);
echo "Plaintext:\n$plaintext\n\n";
echo "Base64 Encrypted:\n$base64Encrypted\n\n

**Comment by rnapier** [comment]
This is the Swift and ObjC repo. Please see the PHP repo to report issues in the PHP implementation. 

https://github.com/RNCryptor/RNCryptor-php
