### ISSUE TITLE
Objective-C code question

### ISSUE THREAD

**Issue by relatedcode** [RNCryptor/RNCryptor#167]

**Comment by relatedcode** [comment]
Objective-C code is over or I just missed something? Thanks!

**Comment by rnapier** [comment]
See the latest release notes: https://github.com/RNCryptor/RNCryptor/releases/tag/RNCryptor-4.0.0

v4 is Swift, but bridges completely to ObjC. For those desiring a pure ObjC implementation, see [v3](https://github.com/RNCryptor/RNCryptor/releases/tag/RNCryptor-3.0.1), which is fully compatible.

If there is strong interest in a updated, pure ObjC implementation (to avoid overhead of linking the Swift standard library, to support pre-Swift platforms), then I'll consider continuing that branch.

**Comment by relatedcode** [comment]
Ok. Thanks!
