### ISSUE TITLE
HmacSHA1 hashing support and  common hmac hashing support from

### ISSUE THREAD

**Issue by lolgear** [RNCryptor/RNCryptor#169]
I want to know about hmac sha1 hashing / common hmac hashing support for Objective-C version.

Also, if it is available, could you add examples or description about hashing?

**Comment by rnapier** [comment]
I don't understand this question. RNCryptor implements a specific encrypted data format. It is not a general-purpose library of cryptographic primitives.

[FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format)
