### ISSUE TITLE
Help wanted: Encrypt string and get specific value?

### ISSUE THREAD

**Issue by galinyonchev** [RNCryptor/RNCryptor#170]
For security purposes I will encrypt some data, including the user password in my application.

My colleagues have chosen scrypt hashing algorithm, for a 64 bytes length, with a fixed seed, then converted to hex.

Hashing "**A12345678Z**" leads to: `25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251`

Seed is “**HeanpyftAkWilfUd**”.

On server, they are using this implementation : [https://github.com/ricmoo/pyscrypt][1]

Example:

    scrypt.hash(“A12345678Z", “HeanpyftAkWilfUd").encode('hex’)

 -> 

    25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251

  [1]: https://github.com/ricmoo/pyscrypt

My question is how to do that in Swift with RNCrypto? If it possible - show me sample code, that will lead hashing "**A12345678Z**" to exactly this:

    25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251

**Comment by rnapier** [comment]
This is a very strange scheme. Using a fixed salt undermines many of the benefits to using scrypt in the first place. You should pick a random salt, apply scrypt, and concat the salt to the hash. It's a very common approach, simple to implement, and dramatically more secure. If you've done things correctly, hashing the same password repeatedly should generate different output every time. Anything that maps a password to exactly one hash is an insecure system.

RNCryptor does not include an scrypt KDF function. It implements a specific data format that relies on PBKDF2 (a similar, but distinct KDF). You will need to find an scrypt implementation in C, Objective-C, or Swift. I'm sure there are several available.

[FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format)
