### ISSUE TITLE
How to use v4 with Objective-C

### ISSUE THREAD

**Issue by s6joui** [RNCryptor/RNCryptor#172]
Hi. I'm trying to use RNCryptor 4 with Objective-C for an iOS app. I've followed the "Installing Manually" instructions but after doing that I don't know how to use RNCryptor.

Do I have to import something? Which file?
```
  NSData *cipherData = [RNCryptor encryptData:plain password:key];
```
This just gives me a Use of undeclared identifier error

Thank you!

**Comment by rnapier** [comment]
Did you add `import "RNCryptor.h"` to your ObjC file. I probably need to explain that for ObjC (it's not necessary or allowed for Swift).

**Comment by s6joui** [comment]
Hi! I add 
```
#import "RNCryptor.h"
```
but it says 'RNCryptor.h' file not found

**Comment by lonkly** [comment]
Issues appears using CocoaPods. Just shows unknown type never the less I did not change anything and I have #import "RNCryptor.h"

**Comment by ljonesfl** [comment]
The answer lies in these answers: http://stackoverflow.com/questions/24206732/cant-use-swift-classes-inside-objective-c

Took me a while to get it right and it was a combination of a couple of different answers  but it works great now.
