### ISSUE TITLE
Use of undeclared identifier 'RNCryptor'

### ISSUE THREAD

**Issue by maxmitch** [RNCryptor/RNCryptor#176]
I have tried both the pod and the manual method of installation of RNCryptor but both I am just getting the error "Use of undeclared identifier 'RNCryptor'". Why is this happening? I have an objective C OSX project. I have tried adding #import "MyApp-Swift.h" #import "RNCryptor" still no luck

**Comment by rnapier** [comment]
If you're using cocoapods, add `@import RNCryptor;`

**Comment by maxmitch** [comment]
Why is that not in the documentation?! That could have saved me an hour...

**Comment by maxmitch** [comment]
Also another small thing to change in the doc:
NSLog(@"ERROR:%@", error);

**Comment by rnapier** [comment]
I've updated the docs.

On Mon, Nov 16, 2015 at 11:01 AM, Max Mitchell <notifications@github.com>
wrote:

> Why is that not in the documentation?! That could have saved me an hour...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RNCryptor/RNCryptor/issues/176#issuecomment-157079346>
> .
>



-- 
Rob Napier
Cocoaphony blog -- http://robnapier.net/blog
iOS Programming Pushing the Limits -- http://robnapier.net/book
