### ISSUE TITLE
Encrypt/Decrypt large files in Objective C using RNcryptor 4.

### ISSUE THREAD

**Issue by pablogeek** [RNCryptor/RNCryptor#177]
I was using RNCryptor 3.0. That is great because you have a handler for manage large files using NSinputStream and NSOutputStream. I can't see this on the swift version. Is there any way to do it async using inputstream and outputstream?

Thanks

**Comment by rnapier** [comment]
My belief is that the new system is easier to use with `NSStream` because I removed the complex callbacks. For example, [here is some example code](https://gist.github.com/rnapier/451fcac4a3323b7c37b1) I'm working on. The read/write loop is:

```
config.input.open()
config.output.open()

var buffer = [UInt8](count: bufferSize, repeatedValue: 0)

let cryptor: RNCryptorType = config.encrypt ?
    RNCryptor.Encryptor(password: config.password) : RNCryptor.Encryptor(password: config.password)

var length = 0

do {
    var inLength = 0
    while true {
        let inLength = config.input.read(&buffer, maxLength: buffer.count)
        guard inLength >= 0 else {
            throw Error.ReadError(config.input.streamError)
        }
        guard inLength > 0 else {
            break
        }
        let inputData = NSData(bytesNoCopy: &buffer, length: inLength)
        let result = try cryptor.updateWithData(inputData)
        let outLength = config.output.write(UnsafePointer(result.bytes), maxLength: result.length)
        guard inLength != outLength else { throw Error.ShortWrite }
    }
}
```

Is there a use case you're finding hard to integrate w/ streams? I'm contemplating a separate framework devoted to transforming streams (where "encrypt" would be one possible transformation). That's my vision for these kinds of problems rather than adding more API to RNCryptor.

**Comment by pablogeek** [comment]
Thanks for your quick response. I'm going to do it with this example and I will let you know. Maybe create RNCryptorFile, and you can do all of the logic of streams inside of this class. That would be good.

**Comment by NathanRussak** [comment]
Just discovered this issue. I had the same needs as @pablogeek, reading and writing large files using streams. @rnapier, your example above was incredibly helpful and got me up and running... but I just thought I'd let you know there are a few little mistakes in it that were holding me up.

**Decryptor Type-o**
There is a simple copy/paste type-o in the line where you were declaring your variable, cryptor. The true and false result of your ternary operator creates an Encryptor. The false condition should be a Decryptor. Like so...
```swift
let cryptor: RNCryptorType = config.encrypt ?
    RNCryptor.Encryptor(password: config.password) : RNDecryptor.Decryptor(password: config.password) 
```

**"Finalized" Data Cap**
After you've finished reading all chunks of data from the NSStream events, it's important that the cryptor's "final data" is written to the output stream before it is closed. If this is not done then the resulting file will be corrupt. For example...
```swift
let finalData = cryptor.finalData()
config.output.write(UnsafePointer(finalData.bytes), maxLength: finalData.length)
```

Figured I'd post this real quick just in case it helps anyone else who attempts to accomplish the same thing as us. Thanks again @rnapier for all of your hard work!

**Comment by rnapier** [comment]
👍
