### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by maxmitch** [RNCryptor/RNCryptor#178]
>"The timestamp service is not available"

Why does RNCryptor require internet? I also had a tester with norton antivirus and the app then didn't work because of rncryptor! Is there a way to capture an RNCryptor error rather than it crashing my app?

**Comment by rnapier** [comment]
I don't know what this means. Can you provide any details and code that demonstrates? There is no timestamp in RNCryptor.

**Comment by maxmitch** [comment]
>/Frameworks/RNCryptor.framework: The timestamp service is not available.

It happens before it reaches my appdelegate!

**Comment by rnapier** [comment]
I have no idea what that means. How did you build this framework? What version of RNCryptor is it? Where does this message appear? Do you have a project you can post that demonstrates the issue? What platform is this? What version?

**Comment by rnapier** [comment]
The only "timestamp server" I know of is for code signing. Are you sure you're not trying to code sign a framework?

**Comment by rnapier** [comment]
I'm really thinking this is a build script you're running. That would explain the "/bin/sh" error and the code signing error. Are you sure you're really running your app itself and not a build script?

**Comment by maxmitch** [comment]
It is a build script you are correct! Any ideas why it is happening? Now instead of it being an issue with the timestamp, it is an error with codesigning rncryptor and it tells me "no identity found"

**Comment by maxmitch** [comment]
http://stackoverflow.com/questions/34356293/error-when-code-signing-framework/34356597#34356597

**Comment by rnapier** [comment]
I believe the latest podspec will resolve this when merged.
