### ISSUE TITLE
Every time different Encrypted string with AES256 and key

### ISSUE THREAD

**Issue by anilios** [RNCryptor/RNCryptor#179]
I am using RNCryptor and eveytime i encrypt a string i get different encrypted string. I need it to be same so that i can save it on server side and match it later for login purpose. 

func getAESEncryptedStringForString(str:String)->String
    {
        let data: NSData = (str.dataUsingEncoding(NSUTF8StringEncoding))!
        let cipherStr = RNCryptor.encryptData(data, password:AesEncryptionKey)
        var aesString = cipherStr.sam_base64EncodedString()
        print("Encrypted AES String \(aesString)")
        
        //Decryption
        let decryptData: NSData = NSData.sam_dataWithBase64String(aesString)
        do {
            let originalData = try RNCryptor.decryptData(decryptData, password: AesEncryptionKey)
            let finalString: NSString = NSString(data:originalData, encoding: NSUTF8StringEncoding)!
            print("Decrypted String \(finalString)")
            
        } catch {
            print(error)
        }

        return aesString
    }

**Comment by rnapier** [comment]
>I am using RNCryptor and eveytime i encrypt a string i get different encrypted string.

Correct. That is an important security feature, and we go to a bit of trouble to make sure this happens.

> I need it to be same so that i can save it on server side and match it later for login purpose.

Encryption is the wrong tool for this job. You mean to use hashing. RNCryptor provides the piece you need.

* Select a per-application salt. For example, you might choose `com.example.mygreatapp`. We'll call this `staticSalt`.
* Select a per-user salt. The most common is the username. We'll call this `userSalt`.
* Concatenate them and convert to `NSData`. We'll call this `salt`.

```swift
let staticSalt = "com.example.mygreatapp"
let userSalt = "bob@example.org"
let salt = (staticSalt + userSalt).dataUsingEncoding(NSUTF8StringEncoding)
```

* Pass that to `keyForPassword`:

```swift
let password = "SomethingTheUserTyped"
let hash = RNCryptor.FormatV3.keyForPassword(password, salt: salt)
```

Send that hash to your server. Then SHA-256 that hash one more time on the server side before storing/comparing to your database.

The client-side piece makes sure that no one can crack the *actual* password, even if they've stolen password hashes from other sites and even if multiple users have the same password. The server-side piece makes sure that even if someone steals your database, they still can't use those tokens to log into your system.

There are no random values in this algorithm, so it is deterministic. You'll get the same result every time.
