### ISSUE TITLE
Searching within encrypted strings

### ISSUE THREAD

**Issue by Datadriven** [RNCryptor/RNCryptor#186]
Hi, 

First of all thank you for the great library, really appreciate your efforts. 

I have a large database that is encrypted, I want to provide a search functionality. I do not want to decrypt the data and store it somewhere for search as it would defy the purpose. 

Hopefully someone can help me and provide a direction for this.

**Comment by rnapier** [comment]
Searchable encryption is a complex and fascinating topic, but the algorithms used by RNCryptor will not help you. You'll want a homomorphic algorithm, which RNCryptor intentionally does not provide.

You'll definitely want to study the topic before selecting a solution. It's easy to make encryption searchable if you make it very insecure. What's difficult is maintaining security at the same time. 

You can also search for database encryption schemes specifically. 

Best of luck. 
Rob

**Comment by Datadriven** [comment]
Thank you for your prompt reply. 

I'll look into the encryption schemes. Keep up the great work.

Have a nice day. 

Vinay.
