### ISSUE TITLE
Use in pure ObjectiveC project (without need to embed Swift libraries)

### ISSUE THREAD

**Issue by VrasidasP** [RNCryptor/RNCryptor#189]
Hi, is there a way to use this library without needing to set `Embedded content contains Swift code` to YES?

My project is in Objective-C (all libraries etc), and adding the Swift libraries makes the build size significantly larger for no apparent reason (eg. http://stackoverflow.com/questions/28741895/xcode-swift-executable-size-much-bigger-than-objective-c-executable) 

Setting it to NO results in: "dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/APP_ID/MYAPP.app/Frameworks/RNCryptor.framework/RNCryptor
  Reason: image not found"

If it can't be done, oh well, we'll have to live with the extra size. :)
Thanks for the excellent library!

**Comment by rnapier** [comment]
Just pull the v3.0.1 release. It's fully supported. https://github.com/RNCryptor/RNCryptor/tree/RNCryptor-3.0.1

If there's interest, I'll pull the ObjC version into its own repository to continue supporting it. I really should have put the Swift code in a new repository, but it's a bit late to fix that.

**Comment by VrasidasP** [comment]
Oh great! Somehow I missed looking into the previous versions.
Thanks! :)
