### ISSUE TITLE
init is deprecated warning in Xcode 7.3

### ISSUE THREAD

**Issue by chrishulbert** [RNCryptor/RNCryptor#195]
Hi, the following lines get warnings in Xcode 7.3, now it's out of beta:

    var cryptorOut = CCCryptorRef() (line 539)
    if cryptor != CCCryptorRef() { (line 556)

The warnings are:

   .../RNCryptor.swift:539:26: 'init()' is deprecated: init() will be removed in Swift 3.  Use `nil` instead

It's not obvious to me how to fix this.

**Comment by heroims** [comment]
#194

**Comment by rnapier** [comment]
Fixed via #194
