### ISSUE TITLE
Conversion between String, NSString and NSData

### ISSUE THREAD

**Issue by pharmpk** [RNCryptor/RNCryptor#197]
I'm trying to understand the use of this library with a simple Swift iOS app. Basically one textfield, a button and output field to encrypt and a second set of textfield, button and outfield to decrypt.

The action on the first button reads the first textfield text as an NSString and encrypts the text and writes it (as a String) into the first outfield and the second input field.

The action on the second button is meant to read the second input field and place the decoded text in the second output field. However, it seems that converting the second input field text (to NSString) changes the 'text' and upsets the process. What it is doing seems logical but not what I want ;-)

I want to be able to encrypt the data in the app and exports it via email or uploaded to a database where it can eventually be decoded as needed.

Any thoughts, suggestions on getting the encrypted data into the second textfield in a form that can be decrypted would be appreciated. Thank you,

The code snippets

`

    @IBAction func encryptText(sender: AnyObject)
    {
        let inputString : NSString = enterField.text!
        let data: NSData = inputString.dataUsingEncoding(NSUTF8StringEncoding)!
        ciphertext = RNCryptor.encryptData(data, password: password)
        print(ciphertext)
        exitField.text = "\(ciphertext)"
        enter2Field.text = "\(ciphertext)"
    }
    
    @IBAction func decryptText(sender: AnyObject)
    {
        let inputString : NSString = enter2Field.text!
        print(inputString)
        ciphertext = inputString.dataUsingEncoding(NSUTF8StringEncoding)!
        print(ciphertext)
        
        do
        {
            let originalData = try RNCryptor.decryptData(ciphertext, password: password)
            resultField.text = "\(NSString(data: originalData, encoding: NSUTF8StringEncoding))"
        }
        catch
        {
            print("Error \(error)")
        }
    
    }

`

**Comment by rnapier** [comment]
The result of this line is an NSData:

    ciphertext = RNCryptor.encryptData(data, password: password)

If you print that, you'll get something like `<00 01 02 ...`. That's just a "description" of the data. It can't be converted back (at least not with the built-in tools). When you convert that string into data again, you get a data that represents the UTF-8 values for "<", "0", "0", " ", "0", "1", ... This isn't your original data.

If you want to print ciphertext, you must encode it in a printable format, such as Base64. For example, see [NSData.base64EncodedString](https://developer.apple.com/reference/foundation/data/2142853-base64encodedstring).
