### ISSUE TITLE
Update swift 3 branch to work with Xcode 8 beta 4

### ISSUE THREAD

**Issue by cesarvarela** [RNCryptor/RNCryptor#200]
It was working with some renaming, but beta 4 has this error that I'm not seeing how to fix it. Maybe someone can help me:

![image](https://cloud.githubusercontent.com/assets/1172479/17453706/9b86e036-5b56-11e6-8183-14263321abc2.png)

**Comment by rnapier** [comment]
Change the "Error" after the colon to Swift.Error.

**Comment by cesarvarela** [comment]
Thanks I'm closing this because of #201
