### ISSUE TITLE
Example workspace playground doesn't work

### ISSUE THREAD

**Issue by sirljan** [RNCryptor/RNCryptor#202]
Hi there!
I cloned RNCryptor repository and opened example KeyDerivation.xcworkspace. I build added project for running and playground shows an error ("RNCryptor is unavailable: cannot find swift declaration for this class") on first line of usage. Import seems to be ok, because I can cmd+click to sources. I was able to create new workspace according to this Apple [guide](https://developer.apple.com/library/mac/recipes/Playground_Help/Chapters/ImportFramework.html) but I still can't make original one working.

![screen shot 2016-08-24 at 18 12 55](https://cloud.githubusercontent.com/assets/419850/17938497/7078c7b8-6a26-11e6-909b-be86ce53e992.png)

**Comment by rnapier** [comment]
Thanks for the report. I'll update the examples.

**Comment by rnapier** [comment]
Fixed in 5.1.0
