### ISSUE TITLE
If you want to use AES 128, What should I do

### ISSUE THREAD

**Issue by Guodadada** [RNCryptor/RNCryptor#204]
If you want to use AES 128, What should I do

**Comment by rnapier** [comment]
I assume you mean "use a 128 bit key" here (AES 128 can mean two different things). 

You would have to modify the code and create you're own incompatible version of RNCryptor. It's a trivial change, but it strongly suggests a misunderstanding about RNCryptor. Why are you trying to do this?  Have you read rhe FAQ entry "Can I use RNCryptor to read and write my non-RNCryptor data format?"

**Comment by rnapier** [comment]
Closing for now; if you have further questions, feel free to reopen.
