### ISSUE TITLE
Decryption returns error 

### ISSUE THREAD

**Issue by maksTheAwesome** [RNCryptor/RNCryptor#205]
Hello guys,

Thank you for your component.

I tried to use it in my NSValueTransformer subclass but here is an issue I'm meeting.

When object is loaded for the first time from the server everything is fine. But if it was updated on the web and updates are pulled from the server - encrypted data get overridden. The next attempt to call decryptData returns the following error: HMACMismatch.

Please advise how can I fix it?

    override class func transformedValueClass() -> AnyClass {
        return NSData.self
    }
    
    override class func allowsReverseTransformation() -> Bool {
        return true
    }
    
    override func transformedValue(value: AnyObject?) -> AnyObject? {
        if let password = password {
            if let dict = value as? [String : AnyObject] {
                let data = try! NSJSONSerialization.dataWithJSONObject(dict, options:[])
                let encryptedData = RNCryptor.encryptData(data, password: password)
                return encryptedData
            }
        }
        assertionFailure("Data can't be nil")
        return nil
    }
    
    override func reverseTransformedValue(value: AnyObject?) -> AnyObject? {
        if let password = password {
            if let data = value as? NSData {
                do {
                    let originalData = try RNCryptor.decryptData(data, password: password)
                    let json = try NSJSONSerialization.JSONObjectWithData(originalData, options:[])
                    return json
                } catch {
                    print("Error decoding data: \(error)")
                }
            }
        }
        assertionFailure("Data can't be nil")
        return nil
    }

**Comment by rnapier** [comment]
Almost certainly the data that you're pulling from the server is not exactly the same data you pushed to the server. My guess would be that you're doing something like Base64 encoding the data when you push it, but failing to Base64 decode it when you pull the data, but it's impossible to know from the code above. You'll need to compare the output of `encryptData` in `tranformedValue` to the later value of `data` in `reverseTransformedValue`. The two must be byte-for-byte identical.

**Comment by maksTheAwesome** [comment]
You are absolutely right that those are not the same. I receive data from server without encryption, then encrypt them (to be save on jailbroken phones also) and store in core data. 

What I expect here is when new data are incoming I encrypt them and override old data but is seems like it affects decryption process as overridden data cannot be decrypted. I'll make a project to demonstrate it next weak if you do not mind to look at it.

**Comment by rnapier** [comment]
Please let me know if you have further issues with this.
