### ISSUE TITLE
Swift 2.3 branch not compatible with Xcode 8

### ISSUE THREAD

**Issue by grangej** [RNCryptor/RNCryptor#207]
I have created a new branch off the tag 4.0 and resolved this but i am unsure on how to create a pull request for this?

**Comment by rnapier** [comment]
To create a PR, fork the project, create a branch on your fork, and then push to your fork. When you visit your fork's GH page, you'll see the option to create a pull request that can pull back to the original. (And Thanks)

https://help.github.com/articles/creating-a-pull-request/

**Comment by rnapier** [comment]
Resolved on the swift2 branch. Please see release 4.1.0. https://github.com/RNCryptor/RNCryptor/tree/RNCryptor-4.1.0
