### ISSUE TITLE
Possible Swift 3.0 update?

### ISSUE THREAD

**Issue by MladenBekavac** [RNCryptor/RNCryptor#212]
Hello,
I would like to know if you will make an Swift 3.0 version update for RNCryptor.
I will soon start working on a iOS 10 project which will need file encryption. I would like to offer my assistance in the update if I can help, and if you need help.

**Comment by rnapier** [comment]
Have you looked at [release 5](https://github.com/RNCryptor/RNCryptor/releases/tag/RNCryptor-5.0.0)?

**Comment by Darkwonder** [comment]
I have tried the release 5 and it didn't work. I have manually downloaded the RNCryptor.swift and added it to the project. The compiler reconized the file BUT it also gave me 35 errors.

I also tried via cocoa pods: `target ‘MyApp’ do
    platform :ios, '9.0'
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    #pod 'Alamofire', '~> 3.5.0'
    pod 'Alamofire', '~> 4.0'
    #pod 'RNCryptor', '~> 5.0.0'
    #pod 'RNCryptor', '5.0.1'
    #pod 'RNCryptor', '~> 5.0'
    #pod 'RNCryptor', '~> 4.0.0-beta'
end
`
All of it didn't work.

**Comment by rnapier** [comment]
I don't know what you mean by "didn't work." What were the 35 errors? What problem did you encounter with CocoaPods?

For CocoaPods, you'll want `~> 5.0`.
