### ISSUE TITLE
Deployment Target is iOS 9 but can be lower

### ISSUE THREAD

**Issue by gbrhaz** [RNCryptor/RNCryptor#213]
When working with Cocoapods this isn't an issue, RNCryptor builds fine in iOS 8 (haven't tried less than that). Working with Carthage, however, the project has a target of iOS 9. 

I'm still on 4.0.0 as I need to use Swift 2.2.

**Comment by rnapier** [comment]
See if this fixes it for you; if so, I'll tag it 4.0.1.

**Comment by gbrhaz** [comment]
Yes, that seems to work. Thanks!
