### ISSUE TITLE
Accessing Swift 3 Version

### ISSUE THREAD

**Issue by codytwinton** [RNCryptor/RNCryptor#214]
Tried using `pod 'RNCryptor', '5.0.0'` in my Pod file for Cocoapods and I'm unable to access.

**Comment by rnapier** [comment]
I don't know much about the podspec. I did update its version number, but I don't know if that's enough to let you see it. If you know anything else that needs doing, I am happy to apply it,  but I generally don't debug CocoaPods.

**Comment by aporat** [comment]
I think you just need to push the podfile with the `pod trunk push [NAME.podspec]` command. I'm also migrating my codebase to swift 3, and seeing the same issue

https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by rnapier** [comment]
`pod trunk push` doesn't succeed because `pod spec lint` doesn't succeed. It complains with:

>“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

It seems related to watchOS (it seems to work for everything else). This is the kind of CP-specific problem that I've tried to avoid getting dragged into. If someone can make `pod spec lint` work, I will be happy to accept a PR. 

Beyond that, RNCryptor is intentionally kept trivial to drop into projects directly so that you should not require a package manager. It does not need, or particularly want, to be shipped as a separate framework.

**Comment by codytwinton** [comment]
Still inaccessible via. Cocoapods. I suppose we can tap into the `master` branch like:

`pod 'RNCryptor', :git => 'https://github.com/RNCryptor/RNCryptor.git', :branch => 'master'`

But, that's the only way I've been able to access version 5

**Comment by codytwinton** [comment]
@rnapier - Thanks for the follow up! I tried running pod install using:

`pod 'RNCryptor', '~> 5.0'`

This is what I received in error logging:

```
[!] Unable to satisfy the following requirements:

- `RNCryptor (~> 5.0)` required by `Podfile`
- `RNCryptor (~> 5.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `RNCryptor (~> 5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

When I run `pod search RNCryptor` in the terminal, this is the result:

```
-> RNCryptor (4.0.0)
   Cross-language AES Encryptor/Decryptor data format.
   pod 'RNCryptor', '~> 4.0.0'
   - Homepage: https://github.com/rnapier/RNCryptor
   - Source:   https://github.com/rnapier/RNCryptor.git
   - Versions: 4.0.0, 4.0.0-beta.1, 3.0.1, 3.0.0, 2.2, 2.1, 2.0, 1.1 [master repo]
```

Looks like the most recent version that Cocoapods is recognizing is version `4.0.0`

**Comment by rnapier** [comment]
5.0.1 is definitely published: https://cocoapods.org/pods/RNCryptor. I don't know how to troubleshoot CocoaPods. I don't use it for anything.

**Comment by codytwinton** [comment]
Finally got this resolved. Must have taken a long time to update on the Cocoapods Specs. Thanks!
