### ISSUE TITLE
Missing 4.1.0 in CocoaPods

### ISSUE THREAD

**Issue by Agies** [RNCryptor/RNCryptor#220]
Good afternoon,

We are still on Swift 2.2 and noticed there is a minor update 4.1.0, however this version has not been pushed to Cocoapods. Is it possible to have this version pushed? Or, is the change non-essential?

Thank you.

**Comment by rnapier** [comment]
Pushed.

```
-> RNCryptor (5.0.1)
   Cross-language AES Encryptor/Decryptor data format.
   pod 'RNCryptor', '~> 5.0.1'
   - Homepage: https://github.com/rnapier/RNCryptor
   - Source:   https://github.com/rnapier/RNCryptor.git
   - Versions: 5.0.1, 4.1.0, 4.0.0, 4.0.0-beta.1, 3.0.1, 3.0.0, 2.2, 2.1, 2.0,
   1.1 [master repo]
```

I'd had some problems with CocoaPods, but the team finally get me setup correctly.
