### ISSUE TITLE
RNCryptor-4.1.0 Deployment Target

### ISSUE THREAD

**Issue by Ericdowney** [RNCryptor/RNCryptor#221]
On RNCryptor-master the deployment target is set to iOS 8.0.  However, the deployment target for RNCryptor-4.1.0 (Swift 2.3) is set to iOS 9.0.  Can the deployment target be set to 8.0 for 4.1.0?

**Comment by rnapier** [comment]
Fixed in 98f442f. Please let me know if you need a full release (4.1.1). I can do that, but I'd planned to have more changes before I did.
