### ISSUE TITLE
AES Decryption

### ISSUE THREAD

**Issue by kamalupasena** [RNCryptor/RNCryptor#222]
Is there a way to decrypt NSData using only a key and IV  using . CTR and noPadding ? if so can you give me an example it would be so great, i have encrypted my data using only a key and iv key but i could find any example on the library to how to do it

**Comment by rnapier** [comment]
Please see the FAQ: https://github.com/RNCryptor/RNCryptor/blob/master/README.md#faq

Q: Can I use RNCryptor to read and write my non-RNCryptor data format?
