### ISSUE TITLE
Not updated for swift 3

### ISSUE THREAD

**Issue by sairasamdanii** [RNCryptor/RNCryptor#223]

**Comment by rnapier** [comment]
I don't understand this issue. The latest release is Swift 3.

**Comment by izotx** [comment]
I second that. Can't make it to work in Xcode 8 and Pod: , '~> 4.0.0-beta:

error: The following binaries use incompatible versions of Swift:
/Users/jchudzynski/Library/Developer/Xcode/DerivedData/CelerationChartApp-cymdccxtjjoaaeecqzfmruvxkayg/Build/Products/Debug-iphonesimulator/CelerationChartApp.app/Frameworks/CryptoSwift.framework/CryptoSwift
/Users/jchudzynski/Library/Developer/Xcode/DerivedData/CelerationChartApp-cymdccxtjjoaaeecqzfmruvxkayg/Build/Products/Debug-iphonesimulator/CelerationChartApp.app/Frameworks/RNCryptor.framework/RNCryptor

**Comment by rnapier** [comment]
`4.0.0-beta` is not Swift 3 compatible. You want `5.0`. Please check the Releases page.
