### ISSUE TITLE
in cache folder,some images are still previewed after encrypting them 

### ISSUE THREAD

**Issue by tranvutuan** [RNCryptor/RNCryptor#225]
My goal is to protect assets such as images from cache folder. I'm currently using Kingfisher to download images. By default, Kingfisher uses `DefaultCacheSerializer` for conversion from image to data and vice versa and then will save data into cache folder. 

In my situation, I was told to [create my own cache serializer](https://github.com/onevcat/Kingfisher/issues/516) which I can encrypt data. Below is how I encrypt and decrypt data using RNCryptor
```
struct NewSerializer: CacheSerializer
{
    public func data(with image: Image, original: Data?) -> Data? {
       let cipherdata = RNCryptor.Encryptor(password: "12").encrypt(data: original!)
        return cipherdata
    }
    
    func image(with data: Data, options: KingfisherOptionsInfo?) -> Image?
    {
        var plaindata = Data()
        do {
            plaindata = try RNCryptor.Decryptor(password: "12").decrypt(data: data)
            return UIImage(data: plaindata, scale:1)
        }
        catch {
            return nil
        }
    }
}
```

After running the application, if I go to the cache folder, I'm able to preview some of the images. Some of them are encrypted since when clicking on it to view, they are just text.

My question are
```
1. Can I use RNCcryptor in my case and if yes, for some reason, it does not work
2. Even though when decrypting using different password from encrypting, I'm still able to retrieve an image.
```

**Comment by rnapier** [comment]
>Some of them are encrypted since when clicking on it to view, they are just text.

This doesn't make sense. The output of `RNCryptor.encrypt()` is never text. It is binary data, just like the image.

I am unfamiliar with Kingfisher. I would first suspect that your encryption code is not actually being called, particularly since you say it seems to ignore the password.

I don't believe there is any RNCryptor issue here; I suspect that you are misconfiguring Kingfisher.
