### ISSUE TITLE
How to implement `RNCryptor` in Objective c?

### ISSUE THREAD

**Issue by bintu1234** [RNCryptor/RNCryptor#226]

**Comment by rnapier** [comment]
I don't understand the question. There is an ObjC implementation of RNCryptor (see the repo at RNCryptor/RNCryptor-objc).

**Comment by bintu1234** [comment]
Sorry my bad i am new to Encryption.I looking for ios -php encryption and decryption one of my friend suggest me this library, How to handle this in my end as well php end any sample for php.
