### ISSUE TITLE
Trying to decrypt with openssl 

### ISSUE THREAD

**Issue by ilyakalinin** [RNCryptor/RNCryptor#228]
Using pod 3.0.0 version

Encryption command:
[RNEncryptor encryptData:data withSettings:kRNCryptorAES256Settings password:@"secret" error:&error];

Trying to decrypt resulting file using openssl command line:
openssl enc -d -aes-256-cbc -in file -out out.txt -k secret

and I get this error: bad magic number

What am I missing? 
Thanks

**Comment by rnapier** [comment]
See the [FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format)

**Comment by ilyakalinin** [comment]
Thanks
