### ISSUE TITLE
What is secret password ?

### ISSUE THREAD

**Issue by SoftwareEngieer** [RNCryptor/RNCryptor#231]
Hi everyone,

i do not understand how to create password in below line. I created password manually but i get HMAC Mismatch error.  What is the logic to create a password?

### NSString *password = @"Secret password";

**Comment by SoftwareEngieer** [comment]
@rnapier  could you plz answer?

**Comment by rnapier** [comment]
I don't understand the question. What do you mean by "I created password manually?" What code did you use to create the password and to use the password?
