### ISSUE TITLE
How can I encrypt string for sending to PHP and how can I decrypt string from PHP

### ISSUE THREAD

**Issue by sicaboy** [RNCryptor/RNCryptor#233]
Hi,

I just got a question. I need to send the encrypted string to PHP. Also after that, PHP will also send an encrypted string back to iOS (Suppose they are using the same password.)
I tried to decrypt the ciphertext, but it failed to display the original string "ABCD1234". 
Could you help me to correct this code, after that I may get idea how it's gonna work then.
Many thanks.

```
        let data = "ABCD1234".data(using: .utf8)
        let password = "Secret password"
        let ciphertext = RNCryptor.encrypt(data: data!, withPassword: password)
        let stringToSendToPHP = ciphertext.base64EncodedString()
        print(stringToSendToPHP)  
```
I will send this text to PHP for decrypting into plaintext with this php. https://github.com/RNCryptor/RNCryptor-php/blob/master/examples/decrypt.php
Does stringToSendToPHP is $base64Encrypted needed by PHP?
        

Then, I will use this PHP to encrypt and pass it into iOS. 
https://github.com/RNCryptor/RNCryptor-php/blob/master/examples/encrypt.php
```
        let encryptedData : Data = stringToSendToPHP.data(using: .utf8)!  // Suppose this is the string encrypted by PHP and now going to be decrypted.
        // Decryption
        do {
            let originalData = try RNCryptor.decrypt(data: encryptedData, withPassword: password)
            print(String(data: originalData, encoding: .utf8) ?? "")
            // ...
        } catch {
            print(error)
        }
```

**Comment by rnapier** [comment]
You've never decoded the Base64 encoding. You treated it as UTF8 encoding. You meant:

    let encryptedData = Data(base64Encoding: stringToSendToPHP)!
