### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by ihorrapalyuk** [RNCryptor/RNCryptor#238]

**Comment by rnapier** [comment]
What is your question!

**Comment by rnapier** [comment]
(Sorry for the exclamation point. Autocorrect.)

**Comment by ihorrapalyuk** [comment]
there is no swift 3.0 support in your lib, can it be added?

2017-02-24 14:45 GMT+02:00 Rob Napier <notifications@github.com>:

**Comment by rnapier** [comment]
The latest version of RNCryptor *only* supports Swift 3. Why do you think there's no Swift 3 support?

**Comment by ihorrapalyuk** [comment]
when in Installing RNCryptor (5.0.1) using cocoa pods i get message
![screen shot 2017-02-28 at 4 28 13 pm](https://cloud.githubusercontent.com/assets/7165232/23409123/19aa1130-fdd3-11e6-86c0-5613970b5130.png)

**Comment by ihorrapalyuk** [comment]
i did that with new, empty project, maybe you just forgot to tag new version for cocoapods

**Comment by rnapier** [comment]
I believe this is tagged. Are you seeing this problem still?
