### ISSUE TITLE
Minor Swift 3 thing?

### ISSUE THREAD

**Issue by kristofer** [RNCryptor/RNCryptor#240]
So at https://github.com/RNCryptor/RNCryptor#swift

you have "encryptData(..." and "decryptData(..." in the README, 
but the new method signatures are  "encrypt(data: ... withPassword:" and "decrypt(data: ... withPassword: "

minor nit.

**Comment by chessboy** [comment]
Actually, it would be great if you could update the example Playground for Swift 3.1 – thanks!

**Comment by chessboy** [comment]
Hi, awesome library! Is it updated for Xcode 8.3 / Swift 3.1? Thanks!

**Comment by rnapier** [comment]
Thanks! Fixed.
