### ISSUE TITLE
How to get IV that generated by RNNCryptor?

### ISSUE THREAD

**Issue by reza-khalafi** [RNCryptor/RNCryptor#242]
Can i get the IV after generating? because i need IV for using in Laravel : Crypt::encrypt('123456');  , i need it for simulate laravel encryption in iOS Swift 3. and you can see this:  [Check it](http://stackoverflow.com/questions/43817329/how-to-encryption-aes-256-cbc-in-ios-swift-3-like-larvel-encrypt-method?noredirect=1#comment74682766_43817329) and this: [Check it](https://github.com/reza-khalafi/LaravelCrypt/blob/master/laravelEncrypt.php)

**Comment by rnapier** [comment]
See [FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format), and following questions.

If you need a PHP implementation of the RNCryptor format, see [RNCryptor/RNCryptor-php](https://github.com/RNCryptor/RNCryptor-php).
