### ISSUE TITLE
AES128 PKCS5Padding

### ISSUE THREAD

**Issue by gdzpf123** [RNCryptor/RNCryptor#243]
iOS can only encrypt in AES128 PKCS7Padding,but JAVA can only encrypt in PKCS5Padding. Do you have any idea to fix it.

**Comment by rnapier** [comment]
PKCS#7 padding and PKCS#5 padding are the same thing. That said, make sure you've read [FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format)
