### ISSUE TITLE
This method(SecRandomCopyBytes) is wrong in Xcode 9 Beta

### ISSUE THREAD

**Issue by SpringAndSummer** [RNCryptor/RNCryptor#244]
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));

![2017-06-06 19 36 14](https://cloud.githubusercontent.com/assets/13082564/26827355/6e080908-4aef-11e7-958a-1f1b0fe8b1a9.png)

**Comment by nealwangzi** [comment]
I meet the same thing.

**Comment by sudoundo** [comment]
also seeing the same issue

**Comment by aizliang** [comment]
me too

**Comment by ben-lings-tessella** [comment]
The iOS 11 SDK has changed the last parameter of its declaration of `SecRandomCopyBytes` from `uint8_t *` to `void *`, so the declarations no-longer match.

**Comment by ben-lings-tessella** [comment]
A workaround for this is to replace the line

```
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));
```

with 

```
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes) __attribute__((weak_import));
```

or, if you need to support building with previous SDKs too, with 

```
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes) __attribute__((weak_import));
#else
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));
#endif
```

**Comment by honkmaster** [comment]
Could this be fixed?

**Comment by prefect42** [comment]
Nice! Rob is on it! 

PS: Nice talk at UIKonf once again!

**Comment by rnapier** [comment]
Can anyone confirm that they're seeing this in the Swift version (this repository currently holds the Swift version, not the ObjC version; that got moved over to RNCryptor-objc).

**Comment by rnapier** [comment]
Note that this is resolved in the ObjC version; please let me know if anyone is having trouble in the Swift version (I don't think you should be).

**Comment by Venkat1128** [comment]
@rnapier I am using pod 'RNCryptor-objc', '~> 3.0' and still i am getting errro at 
extern int SecRandomCopyBytes

I can see that pod version is 3.0.2 and which doent have  below code .
Can you please suggets how can i resolve this issue .
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes) __attribute__((weak_import));
#else
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));
#endif

Thanks,
Venkat

**Comment by rnapier** [comment]
The pod version should be 3.0.5:

https://cocoapods.org/?q=rncryptor-obj

Am I misreading something? (I don't use CocoaPods myself, so this doesn't come up in any of my projects.)
