### ISSUE TITLE
 convert ciphertext to string 

### ISSUE THREAD

**Issue by Marwan88** [RNCryptor/RNCryptor#245]
let data: NSData = ...
let password = "Secret password"
let ciphertext = RNCryptor.encryptData(data, password: password)

how i can convert ciphertext to string ?

**Comment by rnapier** [comment]
See [FAQ: How do I encrypt/decrypt a string?](https://github.com/RNCryptor/RNCryptor#how-do-i-encryptdecrypt-a-string)

**Comment by Marwan88** [comment]
Thank you
