### ISSUE TITLE
RNCryptor  Implementation not found

### ISSUE THREAD

**Issue by iosuma** [RNCryptor/RNCryptor#247]
How to implement the rncrypto in ios objective c

**Comment by rnapier** [comment]
https://github.com/RNCryptor/RNCryptor-objc

**Comment by iosuma** [comment]
Thanks Replay . But i didn't get the file implement file in the file . can you share the document what you have for video encryption and decryption in ios objective c .

**Comment by rnapier** [comment]
RNCryptor is not particularly well suited to video encryption. See "Does RNCryptor support random access decryption?" in the FAQ (in the main README).
