### ISSUE TITLE
Conflicting types error in Xcode 9

### ISSUE THREAD

**Issue by johnryan** [RNCryptor/RNCryptor#248]
Seeing this error after trying to build on Xcode 9. Has anyone else had an issue like this?

```
RNCryptor.m:61:12: Conflicting types for 'SecRandomCopyBytes'
```
![screen shot 2017-07-21 at 3 55 53 pm](https://user-images.githubusercontent.com/416564/28485275-300ec14e-6e2d-11e7-9488-087a6b014e9b.png)

**Comment by ikzjfr0** [comment]
i got this problem too on Xcode9 beta4

**Comment by lsanches** [comment]
iOS 11 changed the signature of that method. RNCryptor devs will need to change it in order to be compatible with the new signature

The function signature of SecRandomCopyBytes has changed 
from: 
-extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));

to:
+extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes) __attribute__((weak_import));

**Comment by gregggreg** [comment]
Replacing that line with this block seems to be a decent solution that will compile properly in Xcode 8 and 9:

`#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 110000
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, void *bytes) __attribute__((weak_import));
#else
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));
#endif
`

**Comment by rnapier** [comment]
@greggreg That sounds like a reasonable solution. Sorry for the delay getting something out; I'll try this and push a new version this week.

**Comment by rnapier** [comment]
What version of RNCryptor are you using? This repository is Swift-only now. The ObjC version was moved to [RNCryptor-objc](https://github.com/RNCryptor/RNCryptor-objc). The current version of RNCryptor-objc shouldn't have this problem (it checks whether you're OS X 10.6 or earlier).

See also https://github.com/RNCryptor/RNCryptor-objc/issues/19

**Comment by adrianevs** [comment]
I have the same issue and replacing that line with the new ones  not helps.

**Comment by rnapier** [comment]
@adrianevs What version of RNCryptor are you using? See note above about move to new repository.

**Comment by itinance** [comment]
@rnapier, just to let you know and answering your question about it: 'RNCryptor-objc' installed by `pod 'RNCryptor-objc'` still has this issue.

**Comment by rnapier** [comment]
@itinance What version of RNCryptor-objc are you using, though? It is incredibly common to fail to update your Cocoapods trunk, so `pod 'RNCryptor-objc'` could be anything.

**Comment by Nandulucky** [comment]
@rnapier , I got the issue when I'm using  'SecRandomCopyBytes' method like,
extern int SecRandomCopyBytes(SecRandomRef rnd, size_t count, uint8_t *bytes) __attribute__((weak_import));

got the issue like, "Conflicting types for 'SecRandomCopyBytes'"

I'm using XCode 9.2 what can I do help me please.

Thanks,
Nandu K

**Comment by taojeff** [comment]
got the issue like, "Conflicting types for 'SecRandomCopyBytes'"

I'm using Xcode 10.2.1 what can I do help me please.

Thanks,
Nandu K

**Comment by rnapier** [comment]
@taojeff  What version of RNCryptor are you using? See note above about move to new repository.

**Comment by taojeff** [comment]
@rnapier RNCryptor 3.0.1

**Comment by rnapier** [comment]
@taojeff See comment immediately before yours that explains this.

**Comment by azav** [comment]
If anyone has this error, try replacing the offending line with this:

    extern int SecRandomCopyBytes(SecRandomRef __nullable rnd, size_t count, void *bytes) __attribute__ ((warn_unused_result));

**Comment by rnapier** [comment]
@azav Please see: https://github.com/RNCryptor/RNCryptor/issues/248#issuecomment-371166831
