### ISSUE TITLE
Using Key and IV, but not HMAC

### ISSUE THREAD

**Issue by gfisch** [RNCryptor/RNCryptor#249]
I'm working with an existing system that has the encrypted version of the AES Key and IV sent as part of the message.  However, there is no capability to use the HMAC key.  I thought there was an older Swift version of RNCryptor that only required the Key and IV.  The current Format3 seems to be close to what I need, but requires the HMAC key.  How should I handle this issue?

Thanks!

**Comment by rnapier** [comment]
See the FAQ: https://github.com/RNCryptor/RNCryptor/blob/master/README.md#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format

You probably want something like CryptoSwift if you're building a custom format.

**Comment by gfisch** [comment]
Thanks, Rob!

I'm already using CryptoSwift, but others in the company felt better with RNCryptor since it was used in other products here.  Having your endorsement means a lot.

Best regards,
Greg
