### ISSUE TITLE
Unable to use with SPM due to versioning

### ISSUE THREAD

**Issue by iamjono** [RNCryptor/RNCryptor#252]
I have an ideal use case for RNCryptor in my Authentication Server project (https://github.com/PerfectServers/Perfect-Authentication-Server) however I can't include RNCryptor as a SPM dependency because of the version numbering.

I'm going to fork and tag it semantic-version-correct, but you might want to adjust the way you do your tag versions :)

**Comment by rnapier** [comment]
I thought we had SPM working now (recently added). What's the numbering issue?

**Comment by rnapier** [comment]
I believe this is resolved in 5.0.3.
