### ISSUE TITLE
Not building on Ubuntu 16.04

### ISSUE THREAD

**Issue by iamjono** [RNCryptor/RNCryptor#253]
Deploying to a Linux server (Ubuntu 16.04)

I'm getting this error...

```
Compile Cryptor Cryptor.c
In file included from /perfectbuild/.build/checkouts/RNCryptor.git--3806749195951240672/Sources/Cryptor/Cryptor.c:1:
/perfectbuild/.build/checkouts/RNCryptor.git--3806749195951240672/Sources/Cryptor/include/RNCryptor.h:188:10: fatal error: 'CoreFoundation/CFAvailability.h' file not found
#include <CoreFoundation/CFAvailability.h>
         ^
1 error generated.
```

**Comment by iamjono** [comment]
LMK if you want me to help you reproduce?

**Comment by rnapier** [comment]
Is CFAvailability.h available on Ububtu? (Is CoreFoundation there?) Is there a replacement for CFAvailability that sets the macros?

**Comment by rnapier** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test thing](https://trello.com/c/eKP80Jrh/1-test-thing)
