### ISSUE TITLE
How to convert ciphertext into string?

### ISSUE THREAD

**Issue by karishmapujara** [RNCryptor/RNCryptor#254]
Hello 

**ciphertext = RNCryptor.encrypt (data: data, withPassword: password)**

I want to store ciphertext as string.
So how can I convert ciphertext into string?
Help me.

**Comment by rnapier** [comment]
Please see the [FAQ: How do I encrypt/decrypt a string?](https://github.com/RNCryptor/RNCryptor#how-do-i-encryptdecrypt-a-string)
