### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by Nathan187** [RNCryptor/RNCryptor#257]
trying to use RNCryptor

/Project Work/Source Code/Work Related/<withheld>/Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift compiled with older version of Swift language (3.0) than previous files (4.0) file '/Project Work/Source Code/Work Related/<withheld>/Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift' for architecture x86_64

tried cleaning build folder....no luck

**Comment by rnapier** [comment]
CryptoSwift is not the same project as RNCryptor. This error refers to CryptoSwift.
