### ISSUE TITLE
Using Version 5.0.1 in current objective C project and in Xcode 9.

### ISSUE THREAD

**Issue by VineetAmipara** [RNCryptor/RNCryptor#258]
I was using version 4.0.0 in my existing objective c project. Now i want to add support of my project for ios 11 so i am just migrating the changes in xcode 9 so it requires compulsory swift 3 or greater version.

I have installed the RNCryptor via CocoaPods.
So when i am updating the RNCryptor version to 5.0.1. It does not actually works and import statements error is coming like use of undeclared identifier RNEncryptorV3.

So how to use the updated version of RNCryptor in xcode 9 in current objective c project...?

And what are the other changes we should be taking care of for iOS 11...

**Comment by rnapier** [comment]
If this is an Objective-C project, use [RNCryptor-objc](https://github.com/RNCryptor/RNCryptor-objc).
