### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by mrobert** [RNCryptor/RNCryptor#259]
Hi there,

  I've been using the tvOS supported RNCryptor from SlaunchaMan/tvos and switched over when you merged it in on Aug 20.  Unfortunately I get, 

"The platform of the target `X` (tvOS 10.0) is not compatible with `RNCryptor (5.0.1)`, which does not support `tvos`."

So for now I've been using the git commit specifically to be able to use it.
"pod 'RNCryptor', :git => 'git@github.com:RNCryptor/RNCryptor.git', :commit => '0d6844d67811d3142891bab393265312ebbdae4a' "

Please let me know when this has been amended.

Kind Regards.

**Comment by rnapier** [comment]
Please try the latest release, 5.0.2. This should include the tvOS fix as well as other build improvements.

**Comment by mrobert** [comment]
Awesome, thanks for the quick response too!
