### ISSUE TITLE
Need solution for AES 128 encryption done in Node JS

### ISSUE THREAD

**Issue by ninjanpotter** [RNCryptor/RNCryptor#265]
Please give a solution for decrypting a AES 128 type encryption done in Node JS. The library which you provided is only for AES 256 type encryption. I am in need of urgent remedy for that. Please give solution for it as soon as possible. 

Note : The algorithm used is aes-128-ecb. 

Thanks.

**Comment by rnapier** [comment]
Please see the [FAQ: Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format).

If your situation is urgent, I provide consulting services to reproduce existing encryption formats in iOS. Please contact at robnapier@gmail.com to discuss rates.
