### ISSUE TITLE
Support PBEWithMD5AndDES

### ISSUE THREAD

**Issue by karnakar** [RNCryptor/RNCryptor#268]
Hi,

Does this support "PBEWithMD5AndDES", if yes how to do the encryption and decryption using PBEWithMD5AndDES.

**Comment by rnapier** [comment]
No, by design. See [FAQ:Can I use RNCryptor to read and write my non-RNCryptor data format?](https://github.com/RNCryptor/RNCryptor#can-i-use-rncryptor-to-read-and-write-my-non-rncryptor-data-format) for full information.
