### ISSUE TITLE
Unable to obtain ASCII hash using RNCryptor.key

### ISSUE THREAD

**Issue by sesdev1** [RNCryptor/RNCryptor#270]
Hello,

I am unable to obtain the ASCII has using the example code. Swift4, Xcode 9.2. Any help would be much appreciated..  hashS is nil.

Code:
let staticSalt = "com.example.mygreatapp"
        let userSalt = "bob@example.org"
        let salt = (staticSalt + userSalt).data(using: String.Encoding.utf8)
        print(salt)
        
        let kDerivationSettings = RNCryptorKeyDerivationSettings(keySize: 256, saltSize: 64, PBKDFAlgorithm: 2, PRF: 3, rounds: 10000, hasV2Password: false)
        let password = "SomethingTheUserTyped"
        let hash = RNCryptor.key(forPassword: password, salt: salt, settings: kDerivationSettings)
            
        print(hash)
        
        let hashS = String(data: hash!, encoding: String.Encoding.utf8)

**Comment by rnapier** [comment]
A key is random bytes, not a UTF-8 encoded String. 

If you want a String from a Data you’ll need to encode it somehow. See the FAQ for more:

https://github.com/RNCryptor/RNCryptor/blob/master/README.md#how-do-i-encryptdecrypt-a-string

(That question refers to cypher text, but keys are the same.)

Rob
