### ISSUE TITLE
How to use RNCryptor in swift iOS 7?

### ISSUE THREAD

**Issue by phucphanJaneto** [RNCryptor/RNCryptor#271]
Hi, 
After I install this library via Cocoapods and add "RNCryptor.h" to Bridging-Header file like this

![screen shot 2018-04-13 at 8 55 49 am 2](https://user-images.githubusercontent.com/37202364/38712852-81845006-3ef8-11e8-8ed0-779c6d076cba.png)

But I can't use any function in swift file. 

![screen shot 2018-04-13 at 8 57 18 am 2](https://user-images.githubusercontent.com/37202364/38712896-b18a9512-3ef8-11e8-8fc6-b45d5217960d.png)

How do I use this library encrypts my data?

**Comment by rnapier** [comment]
Using CocoaPods, you just need to `import RNCryptor`
