### ISSUE TITLE
Crash on deinit of Decryptor in Xcode 10b3

### ISSUE THREAD

**Issue by DavidFaraday** [RNCryptor/RNCryptor#276]
Hi, first of all thank you for this great library!

Im using Swift version for quite some time now and after updating to xcode 10 beta 3 im getting crash every time i run the app. so i created new project in xcode 10 beta 3 and added rncryptor through pods 5.0.3 version. 
in my view did load i have below code

`        // Encryption
        let text = "text to encrypr"
        let data = text.data(using: String.Encoding.utf8)
        let encryptedData = RNCryptor.encrypt(data: data!, withPassword: "pass")
            
        encryptedText = encryptedData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        
        print("original text: \(text)")
        print("encrypted text: \(encryptedText)")
        
        
        var decryptedText = ""
        
        //convert encrypted string to data
        let dataToDecrypt = NSData(base64Encoded: encryptedText, options: NSData.Base64DecodingOptions(rawValue: 0))
        
        // Decryption
        do {
            let originalData = try RNCryptor.decrypt(data: dataToDecrypt! as Data, withPassword: "pass")
            decryptedText = String(data: originalData, encoding: String.Encoding.utf8)!
        } catch {
            print(error)
        }
        
        print("decrypted text: \(decryptedText)")
`

what i want is to encrypt a String, then convert the Data and save it to firebase.
this part works, but when i want to decrypt the String that i saved to firebase the problems start.

if i pass encryptedData that I get from RNCryptor to the decryptor, it works fine, but when i convert my base64 dtring to data and pass it to decryptor it crashes.

`            let originalData = try RNCryptor.decrypt(data: encryptedData, withPassword: "pass")
`
This exact code was working fine on swift 4 and xcode 9.x.

**Comment by DavidFaraday** [comment]
I tried as you said, but that didnt work. the strange thing is it worked 1 time and got same crash after that no matter how many times i run the app.
here is the code in viewDidLoad
```
        let text = "text to encrypr"
        let data = text.data(using: String.Encoding.utf8)
        let encryptedData = RNCryptor.encrypt(data: data!, withPassword: "pass")
        
        encryptedText = encryptedData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        
        print("original text: \(text)")
        print("encrypted text: \(encryptedText)")
        
        
        var decryptedText = ""
        
        //convert encrypted string to data
        let dataToDecrypt = Data(base64Encoded: encryptedText)

        // Decryption
        do {
            let originalData = try RNCryptor.decrypt(data: dataToDecrypt! as Data, withPassword: "pass")
            decryptedText = String(data: originalData, encoding: String.Encoding.utf8)!
        } catch {
            decryptedText = "Failed to decrypt!!!"
        }
        
        print("decrypted text: \(decryptedText)")

```

Screenshot of the crash
<img width="1280" alt="screen shot 2018-07-10 at 07 11 56" src="https://user-images.githubusercontent.com/39456849/42489331-f9ca2f4a-8412-11e8-8412-624748c9745b.png">

Screenshot of the time it worked (code wasnt changed)
<img width="1280" alt="screen shot 2018-07-10 at 07 20 19" src="https://user-images.githubusercontent.com/39456849/42489343-0fb9345e-8413-11e8-9225-388257dfd2f6.png">

I think the problem is with getting back the base64 string from firebase and converting it back to data, somehow its not the same data so decryptor fails to decrypt it. But this code works fine if i run on xCode 9.x and swift 4. also i had tested it xCode 10 Beta 1, it worked as well. on Beta 3 it crashes.

**Comment by rnapier** [comment]
I've reproduced this issue.

**Comment by DavidFaraday** [comment]
I also tested on xCode 10 beta 1 and i can confirm that the code worked fine. its crashes on Beta 3 only

**Comment by rnapier** [comment]
See https://bugs.swift.org/browse/SR-8219

**Comment by rnapier** [comment]
As a temporary fix, making `Credential` non-private will resolve this crash.

```
diff --git a/Sources/RNCryptor/RNCryptor.swift b/Sources/RNCryptor/RNCryptor.swift
index 5d66daa..223ccb6 100644
--- a/Sources/RNCryptor/RNCryptor.swift
+++ b/Sources/RNCryptor/RNCryptor.swift
@@ -614,7 +614,7 @@ internal final class Engine {

 internal typealias V3 = RNCryptor.FormatV3

-private enum Credential {
+/*private*/ enum Credential {
     case password(String)
     case keys(encryptionKey: Data, hmacKey: Data)
 }
```

**Comment by papley** [comment]
We're really curious how you came across the idea of removing 'private' from the enum.

**Comment by papley** [comment]
It does fix our problem.

**Comment by rnapier** [comment]
I found it through minimization. I just kept removing more and more of the code until I found the smallest bit of code that reproduces the problem (see the Swift bug for the final version). I then altered each piece of that code to see what mattered (changing which class, class/struct, private/public/internal, removing/adding properties, removing/adding functions).

**Comment by rnapier** [comment]
Update: This has been resolved in https://github.com/apple/swift/pull/17590, so I expect the next Xcode beta to resolve this issue.

**Comment by rnapier** [comment]
I believe that Xcode10b4 resolves this. Can others confirm? @papley @DavidFaraday

**Comment by DavidFaraday** [comment]
I can confirm its working fine, tested on simulator and iPhone 8

**Comment by johnny77221** [comment]
It's crashing on Xcode 10 beta 3 and working well on beta 4

**Comment by DavidFaraday** [comment]
Does anyone else get this warning? I get it every now and then, after cleaning it it goes away (using xCode 10 beta 4 now, but it appears throughout xCode 10)

<img width="1280" alt="screen shot 2018-07-19 at 19 08 29" src="https://user-images.githubusercontent.com/39456849/42955897-3a96af64-8b87-11e8-9eac-7bcda251cb90.png">

**Comment by rnapier** [comment]
I've seen these warnings with other frameworks in Xcode10. Generally a full clean (cmd-shift-k) or removing DerivedData has cleared them up.
