### ISSUE TITLE
Xcode 10 ß 3 generates code that will crash on macOS when calling RNCryptor.decrypt(Data, String)

### ISSUE THREAD

**Issue by karlkowalskiusr** [RNCryptor/RNCryptor#278]
This is not an issue to be fixed by RNCryptor, this issue is to notify users of RNCryptor that there is a problem with Xcode 10 that Apple is now aware of.

Filed a bug with Apple - Xcode 10 ß 3 macOS app crashes with EXC_BAD_INSTRUCTION on RNCryptor.decrypt( data:Data, password:String)

Crash occurs on macOS 10.13.5 and 10.14 ß 3.

[RNCryptorTest.zip](https://github.com/RNCryptor/RNCryptor/files/2198207/RNCryptorTest.zip)

**Comment by karlkowalskiusr** [comment]
Filed:

Summary: Xcode 10 ß 3 causes crash when calling RNCryptor.decrypt


Steps to Reproduce:
1. Create an Xcode project
2. Add a Podfile with pod init
3. Edit the Podfile to include RNCryptor, latest version
4. Execute pod install to create a workspace with the Xcode project
5. Open the workspace
6. Import RNCryptor to a module
7. Attempt to decrypt an encrypted Data

Expected Results:
Decryption succeeds

Actual Results:
Application Crashes with EXC_BAD_INSTRUCTION

Version/Build:
Xcode 10 ß 3
macOS 10.13.5, macOS 10.14 ß 3

Configuration:
MacBook Pro 15" 2016
2.9 GHz Intel Core i7
16 GB 2133 MHz LPDDR3

**Comment by rnapier** [comment]
Thanks for all the research. See https://github.com/RNCryptor/RNCryptor/issues/276 for the current status and work-around until the next beta.
