### ISSUE TITLE
Not working with Xcode 10 

### ISSUE THREAD

**Issue by ketulbshah** [RNCryptor/RNCryptor#279]
RNCryptor.swift:250:43: Overlapping accesses to 'derivedKey', but modification requires exclusive access; consider copying to a local variable

I have download new release Xcode 10. 
After that I am facing problem with RNCruptor. 
Let me know if anything need from mysids. I already tried this with newly generated project but same problem.

**Comment by HeroMonster** [comment]
Bro, Just update RNCryptor to 5.0.3 it's fixed this problem.
Anyway, I just wonder it's working only with iOS11 up.
It's seem not support below iOS11.
I got this error:
For encrypt:
```
_Extraneous argument labels 'data:withPassword:' in call
Replace 'data: data, withPassword: ' with 'data, '_
```
For Decrypt:
`_Module 'RNCryptor' has no member named 'decrypt'_`

Did you face that problem?

**Comment by ketulbshah** [comment]
Ok thank you. Got it. I have to update repo missed that part.
