### ISSUE TITLE
RNCryptor 5.0.3 Support only iOS 11 and up?

### ISSUE THREAD

**Issue by HeroMonster** [RNCryptor/RNCryptor#280]
Hello, master!
when I run RNCryptor on iOS version below 11. I got this problem 

For encrypt:
Extraneous argument labels 'data:withPassword:' in call
Replace 'data: data, withPassword: ' with 'data, '

For decrypt:
"Module 'RNCryptor' has no member named 'decrypt'"

But if I run on iOS 11 and up it's working good.
Please Check this master, Thanks!

**Comment by rnapier** [comment]
RNCryptor has a minimum target of iOS 8. But this is a compile-time error, which means it can't be happening when you run on iOS at all. When you say "when I run RNCryptor on iOS version below 11," what do you actually mean you're doing? Where does this error appear?
