### ISSUE TITLE
Not able to update to 5.1.0 via Cocoapods

### ISSUE THREAD

**Issue by karishmapujara** [RNCryptor/RNCryptor#287]
Hello

Cocoapods is not upgrading from 5.0.3 to 5.1.0

Latest version is still displaying 5.0.3 in CocoaPods.org
[https://cocoapods.org/pods/RNCryptor](url)

Any suggestions? @rnapier

**Comment by Nibelungc** [comment]
Same here. Maybe you forget to push the podspec. 
https://github.com/CocoaPods/Specs/tree/master/Specs/5/7/f/RNCryptor
There is no 5.1.0 version. Thanks

**Comment by rnapier** [comment]
You're correct. I didn't push the podspec. Should be fixed; sorry for the delay.
