### ISSUE TITLE
has no member 'baseAddress'

### ISSUE THREAD

**Issue by udayatom** [RNCryptor/RNCryptor#288]
RNCryptor.swift:119:98: Value of type 'UnsafeMutablePointer<_>' has no member 'baseAddress'

**Comment by rnapier** [comment]
What compiler are you using, and what version of RNCryptor? The latest RNCryptor is in Swift 5. You can go back a version to get Swift 4.

**Comment by burhanuddin353** [comment]
How to get the version for Swift 4?

I tried the tag 4.0.0 and I got below errors while compiling

![Screen Shot 2019-07-15 at 5 53 52 PM](https://user-images.githubusercontent.com/3624363/61221462-9feb3380-a729-11e9-9813-613c94b2ff93.png)

**Comment by rnapier** [comment]
[Release 5.0.3](https://github.com/RNCryptor/RNCryptor/releases/tag/5.0.3) is the latest that supported Swift 4.1. Release 4.0.0 supported Swift 2.
