### ISSUE TITLE
Building scheme "RNCryptor" in KeyDerivation.xcworkspace

### ISSUE THREAD

**Issue by endresjd** [RNCryptor/RNCryptor#290]
We're seeing errors building KeyDerivation.xcworkspace using the most current carthage and at least Xcode 11 beta 4.

**Fails**:
- Command Line tools: 11M374r
- Carthage: 0.33

**Succeeds**:
- Command Line tools: 10E1001
- Carthage: 0.33

**Comment by rnapier** [comment]
I suspect this is a bug in the Xcode beta. I'll keep an eye on it and make sure to get it fixed one way or another when the GM comes out, but I assume this does not cause any direct problem to you, does it? (There's generally no need to build the playgrounds; they're just there for documentation.)

**Comment by endresjd** [comment]
I was thinking that or Carthage since I notice the build order is different.  When it works, the KeyDerivation is done second, when it fails it is done first.  I solved the problem by using Swift Package Manager, so well done on that!
