### ISSUE TITLE
Out of Memory Error while encrypting Large File

### ISSUE THREAD

**Issue by himanpan** [RNCryptor/RNCryptor#291]
We are trying to encrypt video files on iPhone and facing the out of memory error during encryption.
I saw the "chain streaming" available with other encryptions.
Is is possible to encrypt the file similarly in small chunks with RNCryptor?

**Comment by rnapier** [comment]
Are you using the incremental techniques described at https://github.com/RNCryptor/RNCryptor#incremental-usage? It will hand you back Data objects, which you can deal with as you like.
