### ISSUE TITLE
swift version not supported

### ISSUE THREAD

**Issue by zeroDevOne** [RNCryptor/RNCryptor#292]
Hi, trying to build a proj it always says in xcode 10 swift 5 not supported. 

i download xcode 9.2 
`The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`

i use cocoapods, so i go to pods general page -> build settings and set swift language 4.0 and then swift 3.2 version, but it not give anything, still same error. 
in project general page in build settings i set same version of swift.

how make it work?

**Comment by rnapier** [comment]
I’m unclear about the question. The current version of Xcode is 11.4.1, not 10. Are you having trouble building with the *current* Xcode?

**Comment by zeroDevOne** [comment]
> I’m unclear about the question. The current version of Xcode is 11.4.1, not 10. Are you having trouble building with the _current_ Xcode?

i have macos 10.13.6 and latest version of xcode 10.1 also i was test it on 9.2

**Comment by rnapier** [comment]
The current version of macOS is 10.15.4. You generally should not build on old versions of Xcode, even if you're targeting older platforms. That said, if you have to build with an older version, you'll need to use an older release of RNCryptor, probably [5.0.3](https://github.com/RNCryptor/RNCryptor/releases/tag/5.0.3), which was the last version written in Swift 4.
