### ISSUE TITLE
The operation couldn’t be completed. (RNCryptor.RNCryptor.Error error 2.)

### ISSUE THREAD

**Issue by namanAstapartners** [RNCryptor/RNCryptor#295]
```
 guard let fileData = self.dataAtUrl(url) else { return }
        do {
            let decryptedData = try decryptor.decrypt(data: fileData)
            writeData(decryptedData, toUrl: destinationUrl){ (isSuccess) in
                completion(isSuccess)
            }
        } catch {
            print("Error decrypting File", error.localizedDescription)
        }
```
   
    
    
    Error decrypting File ->  The operation couldn’t be completed. (RNCryptor.RNCryptor.Error error 2.)

**Comment by rnapier** [comment]
The problem here depends on how you've set up your decryptor, which you haven't shown. I expect you've used advanced features incorrectly, but I'd have to see the code. Sorry so late responding to this. If it's still an issue, post some more code and I'll reopen.
