### ISSUE TITLE
What do you use for data?

### ISSUE THREAD

**Issue by HermanKayy** [RNCryptor/RNCryptor#296]
In order to use RNCryptor it seems like you need to create the data yourself off of some arbitrary string. What do you use to determine the string the data is coming from? What is the usage case for the data?

**Comment by rnapier** [comment]
I'm unclear about the question. RNCrypto encrypts arbitrary Data, and outputs Data. It has nothing to do with Strings. If you have a String, you can of course turn it into Data by various means (encoding it to UTF-8 is the most popular), but that has nothing to do with encryption.
