### ISSUE TITLE
PEN TEst Issue : Binary makes use of malloc function

### ISSUE THREAD

**Issue by Gautam-zodape** [RNCryptor/RNCryptor#299]
We are getting error in PEN Test for iOS application which used RNCryptor.
PEN Test check for the security performance of app. We used mobSF (https://mobsf.github.io/Mobile-Security-Framework-MobSF/) tool for the PEN Test.

We get following error in Security PEN Test-
1. strcpy -Used in RNCryptor library while creating crash files
2. strcat - Used in RNCryptor library for concatenation of strings
3. Malloc is used in RNEncrypter for allocating the memory block of given size for itself.

Please fix the issues or provide an update on it if you are going to fix.

**Comment by rnapier** [comment]
1. RNCryptor doesn't create crash files or call strcpy.
2. RNCryptor doesn't concatenate strings or call strcat.
3. RNCryptor doesn't call malloc.

Your tool is broken or you're using it incorrectly or you have the wrong project.

Whoever is performing your security audit does not appear to understand what they are doing. I recommend engaging different security auditors.
