### ISSUE TITLE
OpenSSL with salt

### ISSUE THREAD

**Issue by bigboxsoftware** [RNCryptor/RNCryptor#30]
Apologies if this issue is just a misunderstanding of the protocol, but when using the RNOpenSSLEncryptor and initialising it with a key and IV, although there's no salt value created as part of the password to key generation, a header with a salt is still added as 

- (NSData *)header

always prepends the header and salt.

However, is this needed if the a key/iv are provided instead of a password?     Files I encrypt using other SSL libraries (such as in Ruby) don't add a SALTED header.

Similarly, for RNOpenSSLDecryptor if I initialise it with a key and IV, then

 - (RNDecryptor *)initWithSettings:(RNCryptorSettings)theSettings encryptionKey:(NSData *)anEncryptionKey IV:(NSData *)anIV handler:(RNCryptorHandler)aHandler

sets a value for engine

self.engine = ....

which means consumeHeaderFromData isn't called, and so the header is read instead as part of the data.

If I change the header generator in the encryptor by wrapping it in a conditional:

 if (self.encryptionSalt) {

and returning nil otherwise, everything works perfectly.

Is this a misuse of the class, or is my fix correct?

**Comment by rnapier** [comment]
OpenSSL has moved to https://github.com/rnapier/RNOpenSSLCryptor
