### ISSUE TITLE
How to use the same key Uint8List on swift 

### ISSUE THREAD

**Issue by rulefahd** [RNCryptor/RNCryptor#304]
@rnapier
If you mean on swift code, how can i use the same key of Uint8List(xx) there? To decrypt it correctly?il

 I want to use a customized fixed key  on both (dar, swift) 

Dart(Uint8List(int)) = Swift (????) 

_Originally posted by @rulefahd in https://github.com/RNCryptor/RNCryptor/issues/303#issuecomment-1160761812_

**Comment by rnapier** [comment]
Duplicate of #303
