### ISSUE TITLE
Too low iOS deployment target warning

### ISSUE THREAD

**Issue by ale-gen** [RNCryptor/RNCryptor#307]
While running my iOS app with target 12.0 in Xcode 14 (my app uses RNCryptor integrated by Pods) I get warning `The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.4.99.`. It is caused that Xcode 14 minimum version support is 11.0. Is it possible to raise the deployment target of RNCryptor to 11.0? This [PR](https://github.com/RNCryptor/RNCryptor/pull/306) fixes my issue -> the warning is gone!

**Comment by rnapier** [comment]
Agreed, and merged. I'm sorry for the delay.
