### ISSUE TITLE
[Privacy Manifest] Implementation

### ISSUE THREAD

**Issue by corentios** [RNCryptor/RNCryptor#308]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by rnapier** [comment]
You will need to discuss with your legal compliance team whether this is required for your case. All of the source code is available for audit. It does not make any networking calls, if that is useful in making your determination.

RNCryptor is not on the list of packages you sent me.

**Comment by corentios** [comment]
Hello @rnapier 

Indeed, I see that the article only talks about the SDKs listed, but I have the impression that it's not clear, I've since searched and I came across the answer from an Apple engineer,

What do you think?

"What happens with SDK's that are not in this list? Should every single SDK an app uses to include the privacy manifest file?"

"Any app and third party SDK that collects data, uses required reason API, or both must include a privacy manifest file. If your app uses an SDK not listed but that falls under the mentioned requirements, then this SDK must include a privacy manifest."
Source : https://forums.developer.apple.com/forums/thread/743295?answerId=776587022#776587022

But I think the library is purely a software add-on, so I don't think it's necessary.
