### ISSUE TITLE
Decryption not compatible with older version's encryption

### ISSUE THREAD

**Issue by redleafong** [RNCryptor/RNCryptor#31]
Hi,

I upgraded to the latest version, and it doesn't seem to be able to decrypt data encrypted by an older version. Could you advise? Thanks!

The decryption failed here:

RNDecryptor.m Line 142

`
139   - (BOOL)getSettings:(RNCryptorSettings *)settings forPreamble:(NSData *)preamble
140   {
141     const uint8_t *bytes = [preamble bytes];
142     if (bytes[0] == kRNCryptorFileVersion) {                            // Failed here, kRNCryptorFileVersion is 1, but the encrypted data has a header of "00" (first 2 bytes).
143      *settings = kRNCryptorAES256Settings;`

**Comment by rnapier** [comment]
At this point, going all the way back to v0 is probably out of the question (I haven't even implemented v2 support.)
