### ISSUE TITLE
Usage of SHA-2 for PBKDF2?

### ISSUE THREAD

**Issue by TimoKr** [RNCryptor/RNCryptor#50]
I know that it might not be a security issue, but I've noticed that in the default RNCryptorSettings kRNCryptorAES256Settings SHA1 is used as PRF for PBKDF2.

But as there are no performance differences, I'd recommend to use SHA-2 (e.g. SHA-256) for the key generation. What do you think?

**Comment by rnapier** [comment]
Will be addressed in v4.
