### ISSUE TITLE
Encrypt and Decrypt in Python

### ISSUE THREAD

**Issue by JurajKub** [RNCryptor/RNCryptor#58]
Hello. 
I am encrypting some data in iOS and then sending it to Python server. My python server is returning some garbage data. And then I want to encode reply and send it back to iOS. I am using:
def encrypt(auth_info):
    if auth_info is None:
        return None
    iv = Random.new().read(AES.block_size)
    cipher = AES.new(key[:32], AES.MODE_CFB, iv)
    res = base64.b64encode(iv + cipher.encrypt(auth_info))
    return res

def decrypt(auth_info):
    if auth_info is None:
        return None
    auth = base64.b64decode(auth_info)
    iv = auth[:AES.block_size]
    cipher = AES.new(key[:32], AES.MODE_CFB, iv)
    res = cipher.decrypt(auth[AES.block_size:])
    return res

Can you help me? Thank you.

**Comment by GirirajMulay** [comment]
I have encryption for raw data using RNCryptor in iOS. while decrypting same I am facing issue (Decryption is in python at server side).

Note: Encryption is done using random generated hmac key and encryption key.

Any help will be appreciated.
Thanks in advance

**Comment by rnapier** [comment]
@GirirajMulay I don't believe [RNCryptor-python](https://github.com/RNCryptor/RNCryptor-python) supports key-based encryption. You should open an issue there to request it if you need that.
